/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames;

import MyFrames.MyPanels.ModificationClientPanel;
import MyFrames.MyPanels.NouveauClientPanel;
import MyFrames.MyPanels.SuppressionClientPanel;
import MyFrames.MyPanels.VisionnerClientPanel;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author asus pro
 */
public class FrameClient extends javax.swing.JInternalFrame {
    
    GridBagLayout layout = new GridBagLayout();
    public static NouveauClientPanel nouveauClientPanel;
    VisionnerClientPanel  visionnerClientPanel;
    ModificationClientPanel modificationClientPanel;
    SuppressionClientPanel suppressionClientPanel;
    
    private static FrameClient myInstance;

    public static FrameClient getInstance() {
        if (myInstance == null) {
            myInstance = new FrameClient();
        }
        return myInstance;
    }
    /**
     * Creates new form FrameClient
     */
    public FrameClient() {
        initComponents();
        
        nouveauClientPanel = new NouveauClientPanel();
        visionnerClientPanel = new VisionnerClientPanel();
        modificationClientPanel = new ModificationClientPanel();
        suppressionClientPanel  = new SuppressionClientPanel();
        DynamicPanel.setLayout(layout);
        
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(nouveauClientPanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(visionnerClientPanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(modificationClientPanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(suppressionClientPanel,c);
        
        afficherPanelNouveauClient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarMenuPanel = new javax.swing.JPanel();
        btnNouveau = new javax.swing.JButton();
        btnVisionner = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Client");

        btnNouveau.setText("Nouveau");
        btnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauActionPerformed(evt);
            }
        });

        btnVisionner.setText("Visionner");
        btnVisionner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisionnerActionPerformed(evt);
            }
        });

        jButton3.setText("Modifcation");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Suppression");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarMenuPanelLayout = new javax.swing.GroupLayout(sideBarMenuPanel);
        sideBarMenuPanel.setLayout(sideBarMenuPanelLayout);
        sideBarMenuPanelLayout.setHorizontalGroup(
            sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnNouveau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisionner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        sideBarMenuPanelLayout.setVerticalGroup(
            sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarMenuPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnNouveau)
                .addGap(35, 35, 35)
                .addComponent(btnVisionner)
                .addGap(34, 34, 34)
                .addComponent(jButton3)
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(sideBarMenuPanel, java.awt.BorderLayout.LINE_START);

        DynamicPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauActionPerformed
        afficherPanelNouveauClient();
    }//GEN-LAST:event_btnNouveauActionPerformed

    private void btnVisionnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisionnerActionPerformed
        afficherPanelVisionnerClient();
    }//GEN-LAST:event_btnVisionnerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        afficherPanelModificationClient();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        afficherPanelSuppressionClient();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void afficherPanelNouveauClient()
    {
        nouveauClientPanel.setVisible(true);
        visionnerClientPanel.setVisible(false);
        modificationClientPanel.setVisible(false);
        suppressionClientPanel.setVisible(false);
    }
    
    public void afficherPanelVisionnerClient()
    {
        nouveauClientPanel.setVisible(false);
        visionnerClientPanel.setVisible(true);
        modificationClientPanel.setVisible(false);
        suppressionClientPanel.setVisible(false);
    }
    
    public void afficherPanelModificationClient()
    {
        nouveauClientPanel.setVisible(false);
        visionnerClientPanel.setVisible(false);
        modificationClientPanel.setVisible(true);
        suppressionClientPanel.setVisible(false);
    }
    
    public void afficherPanelSuppressionClient()
    {
        nouveauClientPanel.setVisible(false);
        visionnerClientPanel.setVisible(false);
        modificationClientPanel.setVisible(false);
        suppressionClientPanel.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton btnNouveau;
    private javax.swing.JButton btnVisionner;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel sideBarMenuPanel;
    // End of variables declaration//GEN-END:variables
}
