/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames;

import GestionBancaire.ConnectionBD;
import MyFrames.MyPanels.FicheClientPanel;
import MyFrames.MyPanels.ModificationClientPanel;
import MyFrames.MyPanels.NouveauClientPanel;
import MyFrames.MyPanels.SuppressionClientPanel;
import MyFrames.MyPanels.VisionnerClientPanel;
import static MyFrames.MyPanels.VisionnerClientPanel.fillTable;
import gestionbancaire3.Authentification;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.ResultSet;

/**
 *
 * @author asus pro
 */
public class FrameClient extends javax.swing.JInternalFrame {
    
    GridBagLayout layout = new GridBagLayout();
    public static NouveauClientPanel nouveauClientPanel;
    public static VisionnerClientPanel  visionnerClientPanel;
    public static ModificationClientPanel modificationClientPanel;
    SuppressionClientPanel suppressionClientPanel;
    public static FicheClientPanel ficheClientPanel;
    
    private static FrameClient myInstance;

    public static FrameClient getInstance() {
        if (myInstance == null) {
            myInstance = new FrameClient();
        }
        return myInstance;
    }
    /**
     * Creates new form FrameClient
     */
    public FrameClient() {
        initComponents();
        
        nouveauClientPanel = new NouveauClientPanel();
        visionnerClientPanel = new VisionnerClientPanel();
        modificationClientPanel = new ModificationClientPanel();
        suppressionClientPanel  = new SuppressionClientPanel();
        ficheClientPanel = new FicheClientPanel();
        DynamicPanel.setLayout(layout);
        
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(nouveauClientPanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(visionnerClientPanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(modificationClientPanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(suppressionClientPanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(ficheClientPanel,c);
        
        
        afficherPanelNouveauClient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarMenuPanel = new javax.swing.JPanel();
        btnNouveau = new javax.swing.JButton();
        btnVisionner = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Client");
        setVisible(false);

        btnNouveau.setText("Nouveau");
        btnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauActionPerformed(evt);
            }
        });

        btnVisionner.setText("Visionner");
        btnVisionner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisionnerActionPerformed(evt);
            }
        });

        jButton3.setText("Modifcation");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Suppression");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Fiche client");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Exporter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarMenuPanelLayout = new javax.swing.GroupLayout(sideBarMenuPanel);
        sideBarMenuPanel.setLayout(sideBarMenuPanelLayout);
        sideBarMenuPanelLayout.setHorizontalGroup(
            sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideBarMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNouveau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sideBarMenuPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisionner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarMenuPanelLayout.setVerticalGroup(
            sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNouveau)
                .addGap(31, 31, 31)
                .addComponent(btnVisionner)
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        getContentPane().add(sideBarMenuPanel, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauActionPerformed
        afficherPanelNouveauClient();
    }//GEN-LAST:event_btnNouveauActionPerformed

    private void btnVisionnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisionnerActionPerformed
        afficherPanelVisionnerClient();
    }//GEN-LAST:event_btnVisionnerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        afficherPanelModificationClient();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        afficherPanelSuppressionClient();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        afficherFicheClientPanel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try{
            
            String sql;
            ConnectionBD conn = new ConnectionBD();
            ResultSet rs;
            if(Authentification.id_agence==1){
                sql = "select * from clients;";
                rs = conn.Select(sql);
            }
            else{
                sql = "select * from clients where code_agence=?;";
                rs = conn.initRequetePreparee(sql, true, Authentification.id_agence).executeQuery();
            }
            
            PrintWriter writer = new PrintWriter("clients_file.txt", "UTF-8");
            while(rs.next())
            {
           
               writer.println("nom : " + rs.getString("nom_client") + " prenom: " + rs.getString("prenom_client") + " code_agence: " +rs.getString("code_agence") + " cin_client: " + rs.getString("cin_client"));
            
            }
            writer.close();
            
        }catch(Exception e)
        {
            System.err.println(e);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    public void afficherPanelNouveauClient()
    {
        nouveauClientPanel.setVisible(true);
        visionnerClientPanel.setVisible(false);
        modificationClientPanel.setVisible(false);
        suppressionClientPanel.setVisible(false);
        ficheClientPanel.setVisible(false);
    }
    
    public void afficherPanelVisionnerClient()
    {
        nouveauClientPanel.setVisible(false);
        visionnerClientPanel.setVisible(true);
        modificationClientPanel.setVisible(false);
        suppressionClientPanel.setVisible(false);
        ficheClientPanel.setVisible(false);
    }
    
    public void afficherPanelModificationClient()
    {
        nouveauClientPanel.setVisible(false);
        visionnerClientPanel.setVisible(false);
        modificationClientPanel.setVisible(true);
        suppressionClientPanel.setVisible(false);
        ficheClientPanel.setVisible(false);
    }
    
    public void afficherPanelSuppressionClient()
    {
        nouveauClientPanel.setVisible(false);
        visionnerClientPanel.setVisible(false);
        modificationClientPanel.setVisible(false);
        suppressionClientPanel.setVisible(true);
        ficheClientPanel.setVisible(false);
    }
    
    public void afficherFicheClientPanel()
    {
        nouveauClientPanel.setVisible(false);
        visionnerClientPanel.setVisible(false);
        modificationClientPanel.setVisible(false);
        suppressionClientPanel.setVisible(false);
        ficheClientPanel.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton btnNouveau;
    private javax.swing.JButton btnVisionner;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel sideBarMenuPanel;
    // End of variables declaration//GEN-END:variables
}
