/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames;

import GestionBancaire.ConnectionBD;
import MyFrames.MyPanels.NouveauComptePanel;
import MyFrames.MyPanels.SupprimerComptePanel;
import MyFrames.MyPanels.TransactionComptePanel;
import MyFrames.MyPanels.VisionnerTransactionsPanel;
import gestionbancaire3.Authentification;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.PrintWriter;
import java.sql.ResultSet;

/**
 *
 * @author asus pro
 */
public class FrameCompte extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameCompte
     */
    GridBagLayout layout = new GridBagLayout();
    NouveauComptePanel nouveauComptePanel;
    SupprimerComptePanel supprimerComptePanel;
    VisionnerTransactionsPanel visionnerTransactionsPanel;
    TransactionComptePanel transactionComptePanel;
    
    private static FrameCompte myInstance;

    public static FrameCompte getInstance() {
        if (myInstance == null) {
            myInstance = new FrameCompte();
        }
        return myInstance;
    }
    public FrameCompte() {
        initComponents();
        nouveauComptePanel = new NouveauComptePanel();
        supprimerComptePanel = new SupprimerComptePanel();
        visionnerTransactionsPanel = new VisionnerTransactionsPanel();
        transactionComptePanel =  new TransactionComptePanel();
        DynamicPanel.setLayout(layout);
        
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(nouveauComptePanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(supprimerComptePanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(visionnerTransactionsPanel,c);
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(transactionComptePanel,c);
     
        afficherPanelNouveauCompte();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sideBarMenuPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnTansactions = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Compte");
        setMinimumSize(new java.awt.Dimension(80, 34));
        setNormalBounds(new java.awt.Rectangle(0, 0, 80, 0));
        setPreferredSize(new java.awt.Dimension(713, 377));
        setVisible(false);

        jButton1.setText("Nouveau");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnTansactions.setText("Liste Transaction");
        btnTansactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTansactionsActionPerformed(evt);
            }
        });

        jButton3.setText("Transaction");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarMenuPanelLayout = new javax.swing.GroupLayout(sideBarMenuPanel);
        sideBarMenuPanel.setLayout(sideBarMenuPanelLayout);
        sideBarMenuPanelLayout.setHorizontalGroup(
            sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTansactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sideBarMenuPanelLayout.setVerticalGroup(
            sideBarMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarMenuPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(22, 22, 22)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(btnTansactions)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        getContentPane().add(sideBarMenuPanel, java.awt.BorderLayout.LINE_START);

        DynamicPanel.setMaximumSize(new java.awt.Dimension(85, 23));
        DynamicPanel.setMinimumSize(new java.awt.Dimension(85, 23));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       afficherPanelSuppressionCompte();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       afficherPanelNouveauCompte();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTansactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTansactionsActionPerformed
        afficherPanelTansactionsTable();
    }//GEN-LAST:event_btnTansactionsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        afficherPanelTransactions();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void afficherPanelSuppressionCompte()
    {
        nouveauComptePanel.setVisible(false);
        supprimerComptePanel.setVisible(true);
        visionnerTransactionsPanel.setVisible(false);
        transactionComptePanel.setVisible(false);
        
    }
    
    public void afficherPanelNouveauCompte()
    {
        nouveauComptePanel.setVisible(true);
        supprimerComptePanel.setVisible(false);
        visionnerTransactionsPanel.setVisible(false);
        transactionComptePanel.setVisible(false);
    }
    
    public void afficherPanelTansactionsTable()
    {
        nouveauComptePanel.setVisible(false);
        supprimerComptePanel.setVisible(false);
        visionnerTransactionsPanel.setVisible(true);
        transactionComptePanel.setVisible(false);
    }
    
    public void afficherPanelTransactions()
    {
        nouveauComptePanel.setVisible(false);
        supprimerComptePanel.setVisible(false);
        visionnerTransactionsPanel.setVisible(false);
        transactionComptePanel.setVisible(true);   
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton btnTansactions;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel sideBarMenuPanel;
    // End of variables declaration//GEN-END:variables
}
