/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.MyPanels;

import GestionBancaire.ConnectionBD;
import static MyFrames.MyPanels.VisionnerClientPanel.model;
import gestionbancaire3.Authentification;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author asus pro
 */
public class ModificationClientPanel extends javax.swing.JPanel {
    
    int id_client;
    /**
     * Creates new form ModificationSuppressionClientPanel
     */
    public ModificationClientPanel() {
        initComponents();
         String requete = "select * from agences";
        try {

            ConnectionBD conn = new ConnectionBD();
            ResultSet rs = conn.Select(requete);

            while(rs.next())
            {
                liste_agences.addItem(rs.getString("nom_agence"));
            }

            conn.disconnect();
        } catch (Exception e) {
            System.err.println(e);
        }
            
        if(Authentification.id_agence == 1)
        {
            liste_agences.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cin_field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cin_modification = new javax.swing.JTextField();
        nom_modification = new javax.swing.JTextField();
        prenom_modification = new javax.swing.JTextField();
        btnModifier = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        liste_agences = new javax.swing.JComboBox<>();

        jLabel1.setText("CIN:");

        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("CIN:");

        jLabel3.setText("Nom:");

        jLabel4.setText("Prenom:");

        btnModifier.setText("Modifier");
        btnModifier.setEnabled(false);
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        jLabel5.setText("Agence: ");

        liste_agences.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(cin_field, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nom_modification)
                            .addComponent(prenom_modification, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(cin_modification)
                            .addComponent(liste_agences, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnModifier)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cin_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cin_modification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nom_modification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(prenom_modification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(liste_agences, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnModifier)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String cin = cin_field.getText();
        
         try {
            ConnectionBD conn = new ConnectionBD();
            String sql = "select * from clients where cin_client=?";
            PreparedStatement preparedstm = conn.initRequetePreparee(sql, true, cin);
            ResultSet rs = preparedstm.executeQuery();
            
            if (rs.next()) {
                id_client = rs.getInt("id_client");
                cin_modification.setText(rs.getString("cin_client"));
                nom_modification.setText(rs.getString("nom_client"));
                prenom_modification.setText(rs.getString("prenom_client"));
                
                btnModifier.setEnabled(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "cin inexistant");
            }
            
            conn.disconnect();
        } catch (Exception e) {
            System.err.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        
        String cin = cin_modification.getText();
        String nom = nom_modification.getText();
        String prenom = prenom_modification.getText();
        String nom_agence = liste_agences.getSelectedItem().toString();
        String get_id_agence_sql = "Select code_agence from agences where nom_agence= ?";

        String requete = "update clients set cin_client=?,nom_client=?,prenom_client=?,code_agence=? where id_client=?";
        try {
            ConnectionBD conn = new ConnectionBD();
            PreparedStatement preparedStm = conn.initRequetePreparee(get_id_agence_sql, true,nom_agence);
            ResultSet rs = preparedStm.executeQuery();
            if(rs.next())
            {
                preparedStm = conn.initRequetePreparee(requete, true, cin, nom, prenom,rs.getInt("code_agence"),id_client);
                preparedStm.executeUpdate();

                JOptionPane.showMessageDialog(null, "client modifié");

                //actualiser la table des clients
                VisionnerClientPanel.model.setRowCount(0);
                 try {
                    
                     String sql = "select * from clients";
                     rs = conn.Select(sql);

                    while (rs.next()) {
                         cin = rs.getString("cin_client");
                         nom = rs.getString("nom_client");
                         prenom = rs.getString("prenom_client");
                        double solde_courant = 0, solde_epargne = 0;

                        sql = "select * from comptes where id_client= ?";
                        PreparedStatement prpstm = conn.initRequetePreparee(sql, true, rs.getInt("id_client"));
                        ResultSet rsc = prpstm.executeQuery();
                        while (rsc.next()) {
                            double solde = rsc.getDouble("solde_compte");

                            sql = "select * from comptes_courants where code_compte=?";
                            prpstm = conn.initRequetePreparee(sql, true, rsc.getInt("code_compte"));
                            ResultSet rscc = prpstm.executeQuery();
                            if (rscc.next()) {
                                //compte courant
                                solde_courant = solde;

                            } else { //comptes epargne
                                solde_epargne = solde;
                            }
                        }
                        model.addRow(new Object[]{cin, nom, prenom, solde_courant, solde_epargne});
                    }

                        conn.disconnect();
                    } catch (Exception e) {
                        System.err.println(e);
                    }
                
            }
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
        btnModifier.setEnabled(false);
    }//GEN-LAST:event_btnModifierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModifier;
    private javax.swing.JTextField cin_field;
    private javax.swing.JTextField cin_modification;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> liste_agences;
    private javax.swing.JTextField nom_modification;
    private javax.swing.JTextField prenom_modification;
    // End of variables declaration//GEN-END:variables
}
