/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.MyPanels;

import GestionBancaire.ConnectionBD;
import MyFrames.FrameClient;
import static MyFrames.MyPanels.VisionnerClientPanel.model;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author asus pro
 */
public class SupprimerAgencePanel extends javax.swing.JPanel {

    /**
     * Creates new form SupprimerAgencePanel
     */
    public SupprimerAgencePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        code_field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("code:");

        jButton1.setText("Supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(code_field))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(code_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int code = Integer.parseInt(code_field.getText());

        try {
            ConnectionBD conn = new ConnectionBD();
            String sql = "select * from agences where code_agence=?";
            PreparedStatement preparedstm = conn.initRequetePreparee(sql, true, code);
            ResultSet rs = preparedstm.executeQuery();

            if (rs.next()) {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(null, "Nom: " + rs.getString("nom_agence") + "\nVille: " + rs.getString("ville") + "\nadresse: " + rs.getString("adresse"), "Warning", dialogButton);
                if (dialogResult == JOptionPane.YES_OPTION) {

                    //calculé nombre compte client
                    sql = "select count(*) as nbclient from clients where code_agence = ?";
                    preparedstm = conn.initRequetePreparee(sql, true, code);
                    rs = preparedstm.executeQuery();
                    if (rs.next()) {
                        //si le client n'as pas de compte
                        if (rs.getInt("nbclient") == 0) {
                            //suppression effective
                            sql = "delete from agences where code_agence=?";
                            preparedstm = conn.initRequetePreparee(sql, true, code);
                            preparedstm.executeUpdate();
                            

                            JOptionPane.showMessageDialog(null, "Agence supprimer");
                        } else {
                            //set agence inactif

                            sql = "update agences set inactif=1 where code_agence=?";
                            preparedstm = conn.initRequetePreparee(sql, true, code);
                            preparedstm.executeUpdate();
                            JOptionPane.showMessageDialog(null, "set Agence inactif");
                        }

                        //actualiser la liste des agences
                        //mettre a jour la liste de agences
                        String requete = "select * from agences";
                        try {

                             rs = conn.Select(requete);

                            FrameClient.nouveauClientPanel.getListe_agences().removeAllItems();
                            FrameClient.visionnerClientPanel.getListe_agence().removeAllItems();
                            FrameClient.modificationClientPanel.getListe_agences().removeAllItems();
                            while (rs.next()) {
                                FrameClient.nouveauClientPanel.getListe_agences().addItem(rs.getString("nom_agence"));
                                FrameClient.visionnerClientPanel.getListe_agence().addItem(rs.getString("nom_agence"));
                                FrameClient.modificationClientPanel.getListe_agences().addItem(rs.getString("nom_agence"));
                            }

                            conn.disconnect();
                        } catch (Exception e) {
                            System.err.println(e);
                        }
                        
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "code inexistant");
            }

            conn.disconnect();
        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
