/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.MyPanels;

import GestionBancaire.ConnectionBD;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus pro
 */
public class VisionnerClientPanel extends javax.swing.JPanel {

    
    static  DefaultTableModel model = new DefaultTableModel();
    
    public VisionnerClientPanel() {
        
        initComponents();
        
        fillTable();
        
    }

    public  void fillTable()
    {
        model.addColumn("cin");
        model.addColumn("nom");
        model.addColumn("prenom");
        model.addColumn("compte courant");
        model.addColumn("compte epargne");

        try {
            ConnectionBD conn = new ConnectionBD();
            String sql = "select * from clients";
            ResultSet rs = conn.Select(sql);

            while (rs.next()) {
                String cin = rs.getString("cin_client");
                String nom = rs.getString("nom_client");
                String prenom = rs.getString("prenom_client");
                double solde_courant = 0, solde_epargne = 0;

                sql = "select * from comptes where id_client= ?";
                PreparedStatement prpstm = conn.initRequetePreparee(sql, true, rs.getInt("id_client"));
                ResultSet rsc = prpstm.executeQuery();
                while (rsc.next()) {
                    double solde = rsc.getDouble("solde_compte");

                    sql = "select * from comptes_courants where code_compte=?";
                    prpstm = conn.initRequetePreparee(sql, true, rsc.getInt("code_compte"));
                    ResultSet rscc = prpstm.executeQuery();
                    if (rscc.next()) {
                        //compte courant
                        solde_courant = solde;

                    } else { //comptes epargne
                        solde_epargne = solde;
                    }
                }
                model.addRow(new Object[]{cin, nom, prenom, solde_courant, solde_epargne});
            }

            conn.disconnect();
        } catch (Exception e) {
            System.err.println(e);
        }

        tableClients.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableClients = new javax.swing.JTable();

        tableClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tableClients);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableClients;
    // End of variables declaration//GEN-END:variables
}
