/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyFrames.MyPanels;

import GestionBancaire.ConnectionBD;
import java.io.PrintWriter;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus pro
 */
public class VisionnerTransactionsPanel extends javax.swing.JPanel {

    static  DefaultTableModel model = new DefaultTableModel();
    
    public VisionnerTransactionsPanel() {
        initComponents();
        model.addColumn("code compte");
        model.addColumn("type transaction");
        model.addColumn("montant transaction");
        model.addColumn("date transaction");
        table_transactions.setModel(model);  
    }
    
    public void fill_table(String sql)
    {
        
        model.setRowCount(0);
        try {
            ConnectionBD conn = new ConnectionBD();
            
            ResultSet rs = conn.initRequetePreparee(sql,false,Integer.parseInt(code_field.getText())).executeQuery();
            if(rs.next())
            {
                do{
                    int code_compte = rs.getInt("code_compte");
                    String type_transaction = rs.getString("type_transaction");
                    String montant_transaction = rs.getString("montant_transaction");
                    Date date_transaction = rs.getDate("date_transaction");

                    model.addRow(new Object[]{code_compte, type_transaction, montant_transaction, date_transaction});
                }while (rs.next());
            }
            else JOptionPane.showMessageDialog(null, "Aucune transactions");
            

            conn.disconnect();
        } catch (Exception e) {
            System.err.println(e);
        }

        table_transactions.setModel(model);   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        type_recherche = new javax.swing.JComboBox<>();
        code_field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_transactions = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Rechercher par:");

        type_recherche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIN client", "Code compte" }));

        code_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code_fieldActionPerformed(evt);
            }
        });

        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        table_transactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_transactions);

        jButton2.setText("Exporter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(54, 54, 54)
                            .addComponent(type_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(code_field, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jButton1)))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(type_recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(code_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void code_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_code_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_code_fieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql ="";
        if(type_recherche.getSelectedItem() == "CIN client")
        {
            sql = "select * from transactions where code_compte in (select code_compte from comptes where id_client=(select id_client from clients where cin_client=?));";
        }
        else if(type_recherche.getSelectedItem() == "Code compte")
        {
            sql = "select * from transactions where code_compte=?;";
        }
        
        fill_table(sql);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            
            
            ConnectionBD conn = new ConnectionBD();
            ResultSet rs;
            String sql="select * from transactions where code_compte=(select code_compte from comptes where id_client=(select id_client from clients where cin_client=?));";
            
            rs = conn.initRequetePreparee(sql, true, code_field.getText()).executeQuery();
            PrintWriter writer = new PrintWriter("relever_file.txt", "UTF-8");
            while(rs.next())
            {
               String type= rs.getInt("type_transaction")== 1 ? "Déposer" : "retirer" ;
               writer.println("cin: " + code_field.getText() + " code_compte: " + rs.getString("code_compte") + " type_transaction: " + type + " mantant_transaction: " + rs.getDouble("montant_transaction"));
            
            }
            writer.close();
            
        }catch(Exception e)
        {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_transactions;
    private javax.swing.JComboBox<String> type_recherche;
    // End of variables declaration//GEN-END:variables
}
